### ISSUE TITLE
Working key layout for new Fire Remote Pro

### ISSUE THREAD

**Issue by Bretthansenpc** [fsievers22/esphome-ble-remote#12]
Just thought I would share the working keycodes for the new Fire Remote Pro with the extra buttons.

`    //Keymap for light-up amazon fire remote pro with multiple extra buttons
    static std::map<uint8_t, std::string> KEYMAP {{0x52,"UP"},{0x51,"DOWN"},{0x50,"LEFT"},{0x4f,"RIGHT"},
                                                {0x21,"VOICE"},{0x66,"POWER"},{0xf1,"BACK"},{0x23,"HOME"},
                                                {0x40,"MENU"},{0xb4,"REWIND"},{0xcd,"PLAY_PAUSE"},{0xb3,"FAST_FORWARD"},
                                                {0xe9,"VOL_UP"},{0xea,"VOL_DOWN"},{0xe2,"MUTE"},{0x58,"ENTER"},
                                                {0x80,"HEADPHONES"},{0x9c,"CHN_UP"},{0x9d,"CHN_DOWN"},{0x8d,"TV"},
                                                {0x33,"SETTINGS"},{0x7e,"ONE"},{0x7f,"TWO"},{0xa1,"PRIME"},
                                                {0xa2,"NETFLIX"},{0xa3,"DISNEY"},{0xa4,"HULU"}}; 
`

**Comment by benedikt-bartscher** [comment]
Hey @Bretthansenpc, thanks for the keymaps. Do you have any clue how to use those with the new "Univeral" Hid Support (#15) from @fsievers22 ?

**Comment by Bretthansenpc** [comment]
Unfortunately they only work with the older version

**Comment by Bretthansenpc** [comment]
You can use my fork it has the old version but I didn't add the keymap yet oops haha
