### ISSUE TITLE
Document board compability

### ISSUE THREAD

**Issue by benedikt-bartscher** [fsievers22/esphome-ble-remote#19]
As discussed in https://github.com/fsievers22/esphome-ble-remote/issues/17 not all esp32 boards are supported. Currently i only know about the internal PSRAM limitation, maybe there are more. I think boards with ethernet should work better, because bluetooth/wifi can interfere on esps

**Comment by fsievers22** [comment]
I have added a note in the readme in commit 750fa0995f4108b094774176ca68f89619dab021.
