### ISSUE TITLE
Enhancement - Support for other BLE Remotes - Xiaomi Mi Box

### ISSUE THREAD

**Issue by moh-Brent** [fsievers22/esphome-ble-remote#21]
Hey,
Just wondering if we can use this for other remotes? i.e. Xiaomi Mi Box 3/4, etc.

If so how?  happy to help and do what I can just need to know what?

Cheers
Brent

**Comment by benedikt-bartscher** [comment]
Hey @moh-Brent, i think every HID device should work as long as the keycodes are defined in https://github.com/fsievers22/esphome-ble-remote/blob/master/HidUsageTables.json
If not, you could try adjusting HidUsageTables.json and run https://github.com/fsievers22/esphome-ble-remote/blob/master/generate_cpp_usage_tables.py which should automaticly add all keycodes to cpp files.
