### ISSUE TITLE
Hi Fabian! 

### ISSUE THREAD

**Issue by panchomira** [fsievers22/esphome-ble-remote#5]
First at all, thank you for sharing this. 

Im new here so, im sure im wrong publishing this here, anyways, I wanted to ask you if you can help me.

I have a remote of a Fire Tv stick, with no use because the stick was stolen from my house (can you believe it?). 
I thought that I may be able to use it with my esp32 to turn on automations, lights... etc. but after a while of researching I wasn't able to find a solution using the example that ESPHome gives about an BLE iTag. 

I have no experience in coding, and no experience in custom sensors for ESPHome. Im pretty sure your code will save me, but can you give me a glance of how to use it? Thank you!

**Comment by fsievers22** [comment]
I have improved the documentation, I hope that will help you!

**Comment by panchomira** [comment]
It really does help me!! 

Thank you so much. Looks amazing, and I hope this help others as well.

 If I have time, I would like to make a post in the community forums of HA referencing you and this post. So others may find it as useful as it's to me.

**Comment by fsievers22** [comment]
I am glad I could help you and appreciate your positive feedback. Of course you are welcome to post on the HA community forums.
